# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='about',
            field=models.TextField(default='about'),
            preserve_default=False,
        ),
    ]
